# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This file is the device-specific product definition file for
# crespo. It lists all the overlays, files, modules and properties
# that are specific to this hardware: i.e. those are device-specific
# drivers, configuration files, settings, etc...

# Note that crespo is not a fully open device. Some of the drivers
# aren't publicly available in all circumstances, which means that some
# of the hardware capabilities aren't present in builds where those
# drivers aren't available. Such cases are handled by having this file
# separated into two halves: this half here contains the parts that
# are available to everyone, while another half in the vendor/ hierarchy
# augments that set with the parts that are only relevant when all the
# associated drivers are available. Aspects that are irrelevant but
# harmless in no-driver builds should be kept here for simplicity and
# transparency. There are two variants of the half that deals with
# the unavailable drivers: one is directly checked into the unreleased
# vendor tree and is used by engineers who have access to it. The other
# is generated by setup-makefile.sh in the same directory as this files,
# and is used by people who have access to binary versions of the drivers
# but not to the original vendor tree. Be sure to update both.

# These is the hardware-specific overlay, which points to the location
# of hardware-specific resource overrides, typically the frameworks and
# application settings that are stored in resourced.
DEVICE_PACKAGE_OVERLAYS += device/samsung/u8500-common/overlay

# Libs
PRODUCT_PACKAGES := \
	libstagefrighthw \
	libexifa \
	libjpega \
	com.android.future.usb.accessory

# These are the hardware-specific configuration files
PRODUCT_COPY_FILES := \
	device/samsung/u8500-common/configs/asound.conf:system/etc/asound.conf \
	device/samsung/u8500-common/configs/cspsa.conf:system/etc/cspsa.conf \
	device/samsung/u8500-common/configs/gps.conf:system/etc/gps.conf \
	device/samsung/u8500-common/configs/nvram_net.txt:system/etc/nvram_net.txt \
	device/samsung/u8500-common/configs/sirfgps.conf:system/etc/sirfgps.conf \
	device/samsung/u8500-common/configs/vold.fstab:system/etc/vold.fstab \
	device/samsung/u8500-common/configs/egl.cfg:system/lib/egl/egl.cfg

# Init files
PRODUCT_COPY_FILES += \
	device/samsung/u8500-common/rootdir/init.u8500.rc:root/init.u8500.rc \
	device/samsung/u8500-common/rootdir/prerecovery.rc:root/prerecovery.rc \
	device/samsung/u8500-common/rootdir/ueventd.u8500.rc:root/ueventd.u8500.rc

# Alsa configuration files
PRODUCT_COPY_FILES += \
	device/samsung/u8500-common/usr/share/alsa/alsa.conf:system/usr/share/alsa/alsa.conf \
	device/samsung/u8500-common/usr/share/alsa/cards/aliases.conf:system/usr/share/alsa/cards/aliases.conf \
	device/samsung/u8500-common/usr/share/alsa/pcm/center_lfe.conf:system/usr/share/alsa/pcm/center_lfe.conf \
	device/samsung/u8500-common/usr/share/alsa/pcm/default.conf:system/usr/share/alsa/pcm/default.conf \
	device/samsung/u8500-common/usr/share/alsa/pcm/dmix.conf:system/usr/share/alsa/pcm/dmix.conf \
	device/samsung/u8500-common/usr/share/alsa/pcm/dpl.conf:system/usr/share/alsa/pcm/dpl.conf \
	device/samsung/u8500-common/usr/share/alsa/pcm/dsnoop.conf:system/usr/share/alsa/pcm/dsnoop.conf \
	device/samsung/u8500-common/usr/share/alsa/pcm/front.conf:system/usr/share/alsa/pcm/front.conf \
	device/samsung/u8500-common/usr/share/alsa/pcm/iec958.conf:system/usr/share/alsa/pcm/iec958.conf \
	device/samsung/u8500-common/usr/share/alsa/pcm/modem.conf:system/usr/share/alsa/pcm/modem.conf \
	device/samsung/u8500-common/usr/share/alsa/pcm/rear.conf:system/usr/share/alsa/pcm/rear.conf \
	device/samsung/u8500-common/usr/share/alsa/pcm/side.conf:system/usr/share/alsa/pcm/side.conf \
	device/samsung/u8500-common/usr/share/alsa/pcm/surround40.conf:system/usr/share/alsa/pcm/surround40.conf \
	device/samsung/u8500-common/usr/share/alsa/pcm/surround41.conf:system/usr/share/alsa/pcm/surround41.conf \
	device/samsung/u8500-common/usr/share/alsa/pcm/surround50.conf:system/usr/share/alsa/pcm/surround50.conf \
	device/samsung/u8500-common/usr/share/alsa/pcm/surround51.conf:system/usr/share/alsa/pcm/surround51.conf \
	device/samsung/u8500-common/usr/share/alsa/pcm/surround71.conf:system/usr/share/alsa/pcm/surround71.conf

# configuration files
PRODUCT_COPY_FILES += \
	device/samsung/u8500-common/etc/media_profiles.xml:system/etc/media_profiles.xml
