#!/system/bin/sh
#
# A simple script to copy and/or to enable calling of /system/lib/ste_omxcomponents in /system/lib dir
#
# Just copy the files, symlink doesn't work, don't force
#
mount -o remount,rw /system
echo "Copying OMX components"
echo "Prepare to be verbose"
cp -v /system/lib/ste_omxcomponents/* /system/lib/
mount -o remount,ro /system
exit 0

