#!/system/bin/sh

LIBHEAD="/system/lib/libhead.so"

if [ ! -f $LIBHEAD ]
then
	echo "camerahack: libhead.so not found, symlinking..."
	mount -o remount,rw /system
	ln -s /system/lib/libjhead.so $LIBHEAD
	mount -o remount,ro /system
fi

